[big]*i.     Abstract*

A single I3S data set, referred to as a Scene Layer, is a container for arbitrarily large amounts of heterogeneously distributed 3D geographic data. Scene Layers are designed to be used in mobile, desktop, and server-based workflows and can be accessed over the web or as local files. 

The delivery format and persistence model for Scene Layers, referred to as Indexed 3d Scene Layer (I3S) and Scene Layer Package (SLPK) respectively, are specified in detail in this OGC Community Standard. 

[big]*ii.    Source of the content for this OGC document*
The majority of the content in this OGC document is a direct copy of the content contained at https://github.com/Esri/i3s-spec . No normative changes have been made to the content. This OGC document does contain content not contained at https://github.com/Esri/i3s-spec. Specifically, while derived from content on the https://github.com/Esri/i3s-spec repository, the Abstract, Keywords, Preface, Submitting Organizations, Endorsers, and References sections and Annex B (Bibliography) in this document are not found on the https://github.com/Esri/i3s-spec website.

[big]*iii.   Validity of content*
The Submission Team has reviewed and certified that the “snapshot” content in this Community Standard is true and accurate. <<Add date this time>>

[big]*iv.    Keywords*

The following are keywords to be used by search engines and document catalogues.

ogcdoc, OGC document,  3d, streaming, I3S, point clouds

[big]*v.   Preface*

This document defines profiles of the OGC I3S community standard. These profiles depend on the I3S core standard. These I3S profiles originated from investigations into technologies for rapidly streaming and distributing large volumes of 3D content across enterprise systems that may consist of server components, cloud hosted components, and a variety of client software from desktop to web and mobile applications.

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
====
[big]*vi.    Submitting organizations*

The following organizations submitted this Document to the Open Geospatial Consortium (OGC):

Esri Inc. 

[big]*vii.     Supporting Organizations*

All questions regarding this submission should be directed to the editor or the submitters:

[cols="50e,25e",width="75%",options="header",align="center"]
|===
|Name | Affiliation
|Keith Ryden | Esri
|Carl Reed | Carl Reed & Associates
|===
