== Scope

A single I3S data set, referred to as a scene layer, is a container for arbitrarily large amounts of heterogeneously distributed 3D geographic data. A scene layer is characterized by a combination of layer type and profile to fully describe the behavior of the layer and the manner in which it is realized within the specification.

The I3S format is declarative and extendable, and can be used to represent different types of 3D data. The following layer types have been specified and the standard validated via implementation and production deployments:

- *3D Objects* (e.g. building exteriors, from GIS data as well as 3D models in various formats)
- *Integrated Mesh* (e.g. an integrated surface representing the skin of the earth, from satellite, aerial or drone imagery via dense matching photogrammetric software)
- *Point* (e.g. hospitals or schools, trees, street furniture, signs, from GIS data)
- *Point cloud* (e.g. large point data from LiDAR)
- *Building Scene Layer* (e.g. comprehensive building model including building components)

This documents describes the contents of an I3S scene layer types, also known as profiles.

The core specification of the indexed 3D scene layer (I3S) and scene layer package (*.slpk), as well as the specification for accessing I3S resources as scene service REST endpoints, are described in this standard as open formats.
